const cities = {
  response: {
    count: 88,
    items: [
      {
        id: 1,
        title: "Москва",
      },
      {
        id: 1904692,
        title: "Moscow",
        area: "Latah County",
        region: "Idaho",
      },
      {
        id: 5333546,
        title: "Moscow",
        area: "East Ayrshire",
        region: "Scotland",
      },
      {
        id: 1920414,
        title: "Moscow",
        area: "Lackawanna County",
        region: "Pennsylvania",
      },
      {
        id: 4911089,
        title: "Moscow",
        area: "Lamar County",
        region: "Alabama",
      },
      {
        id: 5005459,
        title: "Moscow",
        area: "Polk County",
        region: "Texas",
      },
      {
        id: 4911090,
        title: "Moscow",
        area: "Marengo County",
        region: "Alabama",
      },
      {
        id: 4934663,
        title: "Moscow",
        area: "Union County",
        region: "Illinois",
      },
      {
        id: 5079147,
        title: "Moscow",
        area: "Washington County",
        region: "Rhode Island",
      },
      {
        id: 5060534,
        title: "Moscow Hill",
        area: "Madison County",
        region: "New York",
      },
      {
        id: 5066388,
        title: "New Moscow",
        area: "Coshocton County",
        region: "Ohio",
      },
      {
        id: 4917326,
        title: "Moscow",
        area: "Jefferson County",
        region: "Arkansas",
      },
      {
        id: 5013525,
        title: "Moscow",
        area: "Augusta County",
        region: "Virginia",
      },
      {
        id: 5097467,
        title: "Moscow",
        area: "Stevens County",
        region: "Kansas",
      },
      {
        id: 4937281,
        title: "Moscow",
        area: "Rush County",
        region: "Indiana",
      },
      {
        id: 4967669,
        title: "Moscow",
        area: "Kemper County",
        region: "Mississippi",
      },
      {
        id: 4980270,
        title: "Moscow",
        area: "Clermont County",
        region: "Ohio",
      },
      {
        id: 5037853,
        title: "Moscow",
        area: "Somerset County",
        region: "Maine",
      },
      {
        id: 5041834,
        title: "Moscow",
        area: "Hillsdale County",
        region: "Michigan",
      },
      {
        id: 5046645,
        title: "Moscow",
        area: "Freeborn County",
        region: "Minnesota",
      },
      {
        id: 5085058,
        title: "Moscow",
        area: "Iowa County",
        region: "Wisconsin",
      },
      {
        id: 5086901,
        title: "Moscow",
        area: "Hancock County",
        region: "West Virginia",
      },
      {
        id: 4943993,
        title: "Moscow",
        area: "Hickman County",
        region: "Kentucky",
      },
      {
        id: 4998280,
        title: "Moscow",
        area: "Fayette County",
        region: "Tennessee",
      },
      {
        id: 5026597,
        title: "Moscow",
        area: "Muscatine County",
        region: "Iowa",
      },
      {
        id: 4956320,
        title: "Moscow",
        area: "Allegany County",
        region: "Maryland",
      },
      {
        id: 4963101,
        title: "Moscow",
        area: "Clay County",
        region: "Missouri",
      },
      {
        id: 4963102,
        title: "Moscow Mills",
        area: "Lincoln County",
        region: "Missouri",
      },
      {
        id: 4980272,
        title: "Moscow Mills",
        area: "Morgan County",
        region: "Ohio",
      },
      {
        id: 5081935,
        title: "Moscow",
        area: "Lamoille County",
        region: "Vermont",
      },
      {
        id: 6181,
        title: "Московский",
      },
      {
        id: 1006492,
        title: "Москово",
        area: "Дюртюлинский район",
        region: "Республика Башкортостан",
      },
      {
        id: 1504599,
        title: "Московка",
        area: "Запорожский район",
        region: "Запорожская область",
      },
      {
        id: 1503263,
        title: "Московское",
      },
      {
        id: 1091598,
        title: "Московское",
        area: "Изобильненский район",
        region: "Ставропольский край",
      },
      {
        id: 1710894,
        title: "Московский",
        area: "Район им. Мир Саида Али Хамадони",
        region: "Хатлонская область",
      },
      {
        id: 1700146,
        title: "Московское",
        area: "Есильский район",
        region: "Акмолинская область",
      },
      {
        id: 1159647,
        title: "Московское",
        area: "Усть-Абаканский район",
        region: "Республика Хакасия",
      },
      {
        id: 1708869,
        title: "Московей",
      },
      {
        id: 1511056,
        title: "Московское",
        area: "Роменский район",
        region: "Сумская область",
      },
      {
        id: 1013119,
        title: "Московский (Московское с/п)",
        area: "Почепский район",
        region: "Брянская область",
      },
      {
        id: 5443524,
        title: "Московская Гора",
        area: "Чашникский район",
        region: "Витебская область",
      },
      {
        id: 1108805,
        title: "Московская",
        area: "Щекинский район",
        region: "Тульская область",
      },
      {
        id: 1511036,
        title: "Московский Бобрик",
        area: "Сумской район",
        region: "Сумская область",
      },
      {
        id: 1158283,
        title: "Московский",
        area: "Тюменский район",
        region: "Тюменская область",
      },
      {
        id: 1008824,
        title: "Москово",
        area: "Учалинский район",
        region: "Республика Башкортостан",
      },
      {
        id: 1702113,
        title: "Московское",
        area: "Костанайский район",
        region: "Костанайская область",
      },
      {
        id: 1030682,
        title: "Московское (Гвардейское с/п)",
        area: "Багратионовский район",
        region: "Калининградская область",
      },
      {
        id: 1048976,
        title: "Московка",
        area: "Добринский район",
        region: "Липецкая область",
      },
      {
        id: 1127719,
        title: "Московская",
        area: "Заларинский район",
        region: "Иркутская область",
      },
      {
        id: 1130426,
        title: "Московская",
        area: "Афанасьевский район",
        region: "Кировская область",
      },
      {
        id: 1012638,
        title: "Московский",
        area: "Мглинский район",
        region: "Брянская область",
      },
      {
        id: 1113621,
        title: "Московский",
        area: "Чесменский район",
        region: "Челябинская область",
      },
      {
        id: 1030689,
        title: "Ново-Московское",
        area: "Багратионовский район",
        region: "Калининградская область",
      },
      {
        id: 1024687,
        title: "Московский 2-й",
        area: "Новохоперский район",
        region: "Воронежская область",
      },
      {
        id: 1123337,
        title: "Московка",
        area: "Хабарский район",
        region: "Алтайский край",
      },
      {
        id: 5427475,
        title: "Мойылды (Московка)",
        area: "Самарский район",
        region: "Восточно-Казахстанская область",
      },
      {
        id: 1058962,
        title: "Московка",
        area: "Городской округ Серпухов",
        region: "Московская область",
      },
      {
        id: 1512484,
        title: "Московка",
        area: "Купянский район",
        region: "Харьковская область",
      },
      {
        id: 5453465,
        title: "Московщина",
        area: "Ошмянский район",
        region: "Гродненская область",
      },
      {
        id: 1031651,
        title: "Московское",
        area: "Славский район",
        region: "Калининградская область",
      },
      {
        id: 1050125,
        title: "Московка (село)",
        area: "Усманский район",
        region: "Липецкая область",
      },
      {
        id: 1136335,
        title: "Московка",
        area: "Назаровский район",
        region: "Красноярский край",
      },
      {
        id: 1060128,
        title: "Московкино",
        area: "Городской округ Шаховская",
        region: "Московская область",
      },
      {
        id: 1108806,
        title: "Московские Выселки",
        area: "Щекинский район",
        region: "Тульская область",
      },
      {
        id: 1025459,
        title: "Московский",
        area: "Таловский район",
        region: "Воронежская область",
      },
      {
        id: 1078757,
        title: "Московский",
        area: "Мартыновский район",
        region: "Ростовская область",
      },
      {
        id: 1082239,
        title: "Московский",
        area: "Скопинский район",
        region: "Рязанская область",
      },
      {
        id: 1122430,
        title: "Московский",
        area: "Крутихинский район",
        region: "Алтайский край",
      },
      {
        id: 1102093,
        title: "Московка",
        area: "Оленинский район",
        region: "Тверская область",
      },
      {
        id: 1127944,
        title: "Московщина",
        area: "Иркутский район",
        region: "Иркутская область",
      },
      {
        id: 3257013,
        title: "Московец",
        area: "Община Карлово",
        region: "Област Пловдив",
      },
      {
        id: 1082238,
        title: "Московка",
        area: "Скопинский район",
        region: "Рязанская область",
      },
      {
        id: 1087147,
        title: "Московка",
        area: "Гагаринский район",
        region: "Смоленская область",
      },
      {
        id: 1144870,
        title: "Московка",
        area: "Убинский район",
        region: "Новосибирская область",
      },
      {
        id: 1148982,
        title: "Московята",
        area: "Верещагинский район",
        region: "Пермский край",
      },
      {
        id: 1050124,
        title: "Московка (деревня)",
        area: "Усманский район",
        region: "Липецкая область",
      },
      {
        id: 1053345,
        title: "Московка",
        area: "Торбеевский район",
        region: "Республика Мордовия",
      },
      {
        id: 1078171,
        title: "Московский",
        area: "Егорлыкский район",
        region: "Ростовская область",
      },
      {
        id: 1157940,
        title: "Московка",
        area: "Нижнетавдинский район",
        region: "Тюменская область",
      },
      {
        id: 1158423,
        title: "Московка",
        area: "Упоровский район",
        region: "Тюменская область",
      },
      {
        id: 1158080,
        title: "Московка",
        area: "Сорокинский район",
        region: "Тюменская область",
      },
      {
        id: 5480579,
        title: "Московка",
        area: "Тисульский район",
        region: "Кемеровская область",
      },
      {
        id: 5488220,
        title: "Московский (Бакланское с/п)",
        area: "Почепский район",
        region: "Брянская область",
      },
      {
        id: 5489155,
        title: "Московское (Пограничное с/п)",
        area: "Багратионовский район",
        region: "Калининградская область",
      },
      {
        id: 5493908,
        title: "Московщина",
        area: "Дубенский район",
        region: "Ровненская область",
      },
      {
        id: 5494881,
        title: "Московское",
        area: "Шосткинский район",
        region: "Сумская область",
      },
      {
        id: 5511255,
        title: "Московский",
        area: "Екатеринбург",
        region: "Свердловская область",
      },
    ],
  },
};

export default cities;
